### ISSUE TITLE
How do I make an <a> tag the size of it's parent tag?

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#1]
```css
/* first of all this is a special case where I hid the image because this is where I want to place my anchor background-image*/ 
.header-inner .grid-item.fm_logo img{
	display:none;
}


.header-inner .grid-item.fm_logo a{
	display:block;
/* this makes it match the parents width and height*/
	width:100%;
	height:100%;
	background: url(https://staging3.somethingturquoise.com/assets/images/logo.png);
  background-repeat: no-repeat;
  /* This is what makes the background image rescale based on the container's size */
  background-size: 100% 100%;
}
```
