### ISSUE TITLE
How to make responsive iframes - using youtube video as example

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#10]
Our video has a 16:9, you can calculate the padding-top for anything using this division problem to find the percentage:

9/16=0.5625

56.25% for padding top

# CSS
```css
.youtube-videos-container{
    overflow: hidden;
  /* 16:9 aspect ratio */
  padding-top: 56.25%;
  position: relative;:
}
.youtube-videos-container iframe {
   border: 0;
   height: 100%;
   left: 0;
   position: absolute;
   top: 0;
   width: 100%;
}
```
# HTML
```html
<div class="youtube-videos-container">
  <iframe src="https://www.youtube.com/embed/6z_x-bu28JI" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
</div>
```
