### ISSUE TITLE
How to Install Custom Fonts on Wesbite

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#11]
First upload the font files to a dedicated folder, preferably in uploads since you will have permissions to load fonts from **wp-content/uploads** directory

```css
@font-face {
    font-family: "P22ArtsAndCrafts";
    src: url("./wp-content/uploads/fonts/p22-arts.eot"); /* IE9 Compat Modes */
    src: url("./wp-content/uploads/fonts/p22-arts.eot?#iefix") format("embedded-opentype"), /* IE6-IE8 */
      url("./wp-content/uploads/fonts/p22-arts.otf") format("opentype"), /* Open Type Font */
      url("./wp-content/uploads/fonts/p22-arts.svg") format("svg"), /* Legacy iOS */
      url("./wp-content/uploads/fonts/p22-arts.ttf") format("truetype"), /* Safari, Android, iOS */
      url("./wp-content/uploads/fonts/p22-arts.woff") format("woff"), /* Modern Browsers */
      url("./wp-content/uploads/fonts/p22-arts.woff2") format("woff2"); /* Modern Browsers */
    font-weight: normal;
    font-style: normal;
  }
```

**Comment by Michaelh818** [comment]
```css
/* Custom Font Installation - Bebas */
@font-face {
    font-family: "Bebas";
    src: url("https://caspianclients.com/arpelmedspa/wp-content/uploads/fonts/BebasNeue-Regular.eot"); /* IE9 Compat Modes */
    src: url("https://caspianclients.com/arpelmedspa/uploads/fonts/BebasNeue-Regular.eot?#iefix") format("embedded-opentype"), /* IE6-IE8 */
      url("https://caspianclients.com/arpelmedspa/wp-content/uploads/fonts/BebasNeue-Regular.otf") format("opentype"), /* Open Type Font */
      url("https://caspianclients.com/arpelmedspa/wp-content/uploads/fonts/BebasNeue-Regular.svg") format("svg"), /* Legacy iOS */
      url("https://caspianclients.com/arpelmedspa/wp-content/uploads/fonts/BebasNeue-Regular.ttf") format("truetype"), /* Safari, Android, iOS */
      url("https://caspianclients.com/arpelmedspa/wp-content/uploads/fonts/BebasNeue-Regular.woff") format("woff"), /* Modern Browsers */
      url("https://caspianclients.com/arpelmedspa/wp-content/uploads/fonts/BebasNeue-Regular.woff2") format("woff2"); /* Modern Browsers */
    font-weight: normal;
    font-style: normal;
  }


*,a,p,li,span,h1,h2,h3,h4,h5,h6{
	font-family: Bebas !important;
	letter-spacing:3px !important;
}
.fa {
	  font-family: FontAwesome !important;
}

#wpadminbar * {
    letter-spacing: normal !important;
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif !important;
}

/* don't override wordpress stuff and icons for the theme */
#wpadminbar .ab-icon, #wpadminbar .ab-item:before, #wpadminbar>#wp-toolbar>#wp-admin-bar-root-default .ab-icon, .wp-admin-bar-arrow {
    font-family: 'dashicons' !important;
	letter-spacing: normal !important;
}
/* don't override font awesome icons for the theme */
.fa {
    display: inline-block;
}

nav .fa, .timely * i{
    display: inline-block;
	  font: normal normal normal 14px/1 FontAwesome !important;
}

```

**Comment by Michaelh818** [comment]
```css
/* Custom Font Installation - SFProDisplay-Regular */
@font-face {
    font-family: "SFProDisplay-Regular";
    src: url("https://caspianclients.com/malekian/wp-content/uploads/fonts/SFProDisplay-Regular.eot"); /* IE9 Compat Modes */
    src: url("https://caspianclients.com/malekian/uploads/fonts/SFProDisplay-Regular.eot?#iefix") format("embedded-opentype"), /* IE6-IE8 */
      url("https://caspianclients.com/malekian/wp-content/uploads/fonts/SFProDisplay-Regular.otf") format("opentype"), /* Open Type Font */
      url("https://caspianclients.com/malekian/wp-content/uploads/fonts/SFProDisplay-Regular.svg") format("svg"), /* Legacy iOS */
      url("https://caspianclients.com/malekian/wp-content/uploads/fonts/SFProDisplay-Regular.ttf") format("truetype"), /* Safari, Android, iOS */
      url("https://caspianclients.com/malekian/wp-content/uploads/fonts/SFProDisplay-Regular.woff") format("woff"), /* Modern Browsers */
      url("https://caspianclients.com/malekian/wp-content/uploads/fonts/SFProDisplay-Regular.woff2") format("woff2"); /* Modern Browsers */
    font-weight: normal;
    font-style: normal;
  }


*,a,p,li,span,h1,h2,h3,h4,h5,h6{
	font-family: SFProDisplay-Regular !important;
	letter-spacing:3px !important;
}
.fa {
	  font-family: FontAwesome !important;
}
.qode_icon_font_elegant {
	font-family:ElegantIcons !important;
}

#wpadminbar * {
    letter-spacing: normal !important;
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif !important;
}

/* don't override wordpress stuff and icons for the theme */
#wpadminbar .ab-icon, #wpadminbar .ab-item:before, #wpadminbar>#wp-toolbar>#wp-admin-bar-root-default .ab-icon, .wp-admin-bar-arrow {
    font-family: 'dashicons' !important;
	letter-spacing: normal !important;
}
/* don't override font awesome icons for the theme */
.fa {
    display: inline-block;
}

nav .fa, .timely * i{
    display: inline-block;
	  font: normal normal normal 14px/1 FontAwesome !important;
}
```
