### ISSUE TITLE
WPFront Notification Bar - CSS for installing sticky on site

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#12]
# Caspian Services Example - https://www.caspianservices.net/
```css
/* office closed notification - css

	header.main-header {
    	margin-top: 33px;
	}
	#wnb-bar {
		border-bottom: 0px !important;
	}
	#sdrn_bar {
		margin-top:33px;
	}

	@media (min-width:992px){
		.page-template-page-home-php .main {
			margin-top: 96px;
		}
		.main {
			margin-top:96px;
		}
	}
	@media (min-width:962px) and (max-width:991px){
		.main {
			margin-top:182px;
		}
	}
	@media (max-width:606px){
		#sdrn_bar, #sdrn_menu_ul {
			margin-top:66px;
		}
	}

@media (max-width: 568px){
#sdrn_bar {
    margin-top: 33px;
}
}
end of office closed notification */
```

**Comment by Michaelh818** [comment]
https://motenlaw.com/ - example
Here we just pushed the stick header down, it remains one size its much easier than caspian setup
```css
.et_fixed_nav #main-header, .et_fixed_nav #top-header {
    position: fixed;
    top: 40px !important;
}
.phone-number-top-notifcation-bar{
color:#fff !important;
}
```
