### ISSUE TITLE
What are block level i.e. h1,h2,h3,h4,h5,h6 and inline level i.e. span elements

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#2]
srcs:
https://stackoverflow.com/questions/4041820/are-h1-h2-h3-h4-tags-block-or-inline-elements
https://stackoverflow.com/questions/39547412/same-font-size-for-h1-and-h2-in-article

```css 
.single-post   .wp-content h4{
	font-size:2.295em;
  color: #8DCEC1; /*turquoise*/
}
.single-post   .wp-content h4 span.center {
	font-size:100%;
	color: #8DCEC1; /*navy blue*/
}

.single-post   .wp-content h3{
	font-size:2.295em;
	color: #395a7c; /*navy blue*/
}



.single-post   .wp-content h3 span.center {
	font-size:100%;
	color: #395a7c; /*navy blue*/
}

 
 

.single-post   .wp-content h2
{
	font-size:2.295em;
	color: #e3c9b9; /*peach*/
} 
/* overwrites peach for those  hashtags not included in content..*/
div.title h2 {
	color: #395A7B !important;
}
```
![image](https://user-images.githubusercontent.com/9604573/67536637-ffdc6900-f68c-11e9-957b-d86b9c1c7b4a.png)
