### ISSUE TITLE
Hide All png and jpg images using advanced css selectors

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#3]
```css
img[src*=".jpg"], img[src*=".png"]  {
    display: none;
}
```
you can do more with this because this checks the source for any given string

# Syntax
`img[src*=".jpg"]`
the syntax is
`<element>[elementAttribute*="substring"]`
