### ISSUE TITLE
Prevent Navbar Menu Items Overflow

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#4]
Prevent Navbar Menu Items Overflow by simply changing .site-nav in the below example to w.e. it is relevant.  The second example demonstrates this.  Of course it is site based.

# StockShield.com
```css
@media (max-width:1476px){
header  .site-nav>ul>li>a {
    padding:0 20px!important;
}
}

@media (max-width:1376px){
header  .site-nav>ul>li>a {
    padding:0 17px!important;
}
}

@media (max-width:1276px){
header  .site-nav>ul>li>a {
    padding:0 14px!important;
}

header .header_inner_left {
	  /*45px is default*/
    left:45px!important;
}
}


@media (max-width:1176px) and (min-device-width: 1000px) {
header  .site-nav>ul>li>a {
    padding:0 8px!important;
}

header .header_inner_left {
	  /*45px is default*/
    left:25px!important;
}
}

/*
@media (max-width:1476px){
header:not(.sticky):not(.scrolled) .site-nav>ul>li>a {
    padding:0 20px!important;
}
}

@media (max-width:1376px){
header:not(.sticky):not(.scrolled) .site-nav>ul>li>a {
    padding:0 17px!important;
}
}

@media (max-width:1276px){
header:not(.sticky):not(.scrolled) .site-nav>ul>li>a {
    padding:0 14px!important;
}
*/
/* header .header_inner_left { */
	  /*45px is default*/
/*     left:45px!important;
}
}
 */


@media (max-width:1176px) and (min-device-width: 1000px) {
header:not(.sticky):not(.scrolled) .site-nav>ul>li>a {
    padding:0 8px!important;
}

header .header_inner_left {
	  /*45px is default*/
    left:25px!important;
}
}
```

# Warehouse1productions.com
```css
@media (max-width:1476px){
header  nav.main_menu>ul>li>a {
    padding:0 20px!important;
}
}

@media (max-width:1376px){
header  nav.main_menu>ul>li>a {
    padding:0 17px!important;
}
}

@media (max-width:1276px){
header  nav.main_menu>ul>li>a {
    padding:0 14px!important;
}

header .header_inner_left {
	  /*45px is default*/
    left:45px!important;
}
}


@media (max-width:1176px) and (min-device-width: 1000px) {
header  nav.main_menu>ul>li>a {
    padding:0 8px!important;
}

header .header_inner_left {
	  /*45px is default*/
    left:25px!important;
}
}

/*
@media (max-width:1476px){
header:not(.sticky):not(.scrolled) nav.main_menu>ul>li>a {
    padding:0 20px!important;
}
}

@media (max-width:1376px){
header:not(.sticky):not(.scrolled) nav.main_menu>ul>li>a {
    padding:0 17px!important;
}
}

@media (max-width:1276px){
header:not(.sticky):not(.scrolled) nav.main_menu>ul>li>a {
    padding:0 14px!important;
}
*/
/* header .header_inner_left { */
	  /*45px is default*/
/*     left:45px!important;
}
}
 */


@media (max-width:1176px) and (min-device-width: 1000px) {
header:not(.sticky):not(.scrolled) nav.main_menu>ul>li>a {
    padding:0 8px!important;
}

header .header_inner_left {
	  /*45px is default*/
    left:25px!important;
}
}
```
