### ISSUE TITLE
How to rotate something in CSS using transform Properties

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#7]
```css
.mkdf-property-list-holder.mkdf-pl-standard-shader article .mkdf-pli-image .mkdf-pli-category-holder {
    display: inline-block;
    position: absolute;
    top: 15px;
    left: 15px;
    z-index: 10;
    transform-origin: 0 0;
    -webkit-transform: rotate(270deg) translateX(-100%);
    -moz-transform: rotate(270deg) translateX(-100%);
    transform: rotate(270deg) translateX(-100%);
}
```
![image](https://user-images.githubusercontent.com/9604573/84929547-d2618700-b084-11ea-9d66-0135cad5b13d.png)
```html
<div class="mkdf-pli-category-holder">
  <a itemprop="url" class="mkdf-pli-category" href="http://www.hunterhomesla.com/property-category/sold/">Sold</a>
</div>
```
