### ISSUE TITLE
Custom Navbar Backgrounds in Bridge (Combining a Background Image, with liner-gradient)

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#8]
https://caspianclients.com/restoreandbuild/
```css
aside.vertical_menu_area.with_scroll{
/*     background-image: url(https://caspianclients.com/restoreandbuild/wp-content/uploads/2020/09/warm-white-masaic-matte-1x1-26px.png); */
/* 	  background-image: url(https://caspianclients.com/restoreandbuild/wp-content/uploads/2020/09/AdobeStock_296302526_Preview-260x75-1.jpg); */
/* 	the approach for screens longer than 903px is to have liner gradent from left to right */
	background-image:url(https://caspianclients.com/restoreandbuild/wp-content/uploads/2020/09/AdobeStock_296302526_Preview-260x903-1.jpg), linear-gradient(to right, rgba(136,136,136, .82), rgba(136,136,136, 1));
/* 	background-color:rgba(136,136,136, 1); */
    background-repeat:repeat-x;
}
```
