### ISSUE TITLE
When a Admin is logged into Wordpress Social Media Icons are Hidden In Bridge Qode Theme

### ISSUE THREAD

**Issue by Michaelh818** [Michaelh818/CSS#9]
```css
/* not sure why bridges theme qode social is hidden when admin is logged in for bridge very irritating */
.q_social_icon_holder, .simple_social, .qode_icon_font_elegant{
	display:inline-block !important;
}
```
